# Generated by Django 6.0.1 on 2026-01-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
