# Generated by Django 6.0.1 on 2026-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_question_choice_a_question_choice_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='List of course topics/modules'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Track topic completion: {topic_index: True/False}'),
        ),
    ]
